apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  ports:
    - name: cassandra
      port: 9042
      targetPort: 9042
  selector:
    io.kompose.service: cassandra
