apiVersion: v1
kind: Service
metadata:
  name: codeforces-web
  labels:
    app: codeforces-web
spec:
  selector:
    app: codeforces-web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  type: ClusterIP
