apiVersion: v1
kind: Service
metadata:
  name: codeforces-api
  labels:
    app: codeforces-api
spec:
  selector:
    app: codeforces-api
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
  type: ClusterIP
