apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: micro-postgres
  namespace: default
spec:
  teamId: "micro"
  numberOfInstances: 1

  volume:
    size: 10Gi
    storageClass: ""   # use default

  users:
    app_user: []       # creates user without superuser/admin privileges

  databases:
    micro_auth: app_user

  postgresql:
    version: "15"

  patroni:
    pg_hba:
      - local replication standby trust
      - host replication standby 0.0.0.0/0 md5
      - host replication standby ::0/0 md5
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5
      - local all all trust

  allowedSourceRanges:
    # Replace with your actual node subnet — from your logs the node is:
    # 192.168.184.64
    # So likely /24 or /16
    - 192.168.184.0/24
    # You can also allow the entire cluster easily
    # - 10.0.0.0/8

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1"
      memory: "500Mi"
